name: pr-code-coverage-visualizer
description: Take generated code coverage files and visualize uncovered lines in a PR comment

inputs:
  files:
    description: One or multiple coverage files. Can be multiple lines. Glob patterns are supported.
    required: true
  update-comment:
    description: Whether to update an existing comment instead of creating a new one
    required: false
    default: 'true'
  show-changed-lines-only:
    description: If part of a PR, filter coverage data against changed lines
    required: false
    default: 'true'
  show-glob-only:
    description: Select subdirectories to show coverage data for
    required: false
    default: '**'
  source:
    description: Fallback source directory for resolving file paths from coverage files
    required: false
    default: ${{ github.workspace }}
  token:
    description: GitHub token for API access
    required: true
    default: ${{ github.token }}

outputs:
  line-coverage:
    description: The overall line coverage percentage
  branch-coverage:
    description: The overall branch coverage percentage
  pr-line-coverage:
    description: The coverage of the changes of this PR. Equal to the overall line coverage, if not executed on a PR
  pr-branch-coverage:
    description: The overall branch coverage percentage. Equal to the overall line coverage, if not executed on a PR

runs:
  using: 'node24'
  main: 'dist/index.js'
