import type { CoverageMetrics, FileCoverage, LineCoverage, PackageCoverage } from '../coverage/model.js'

/** Emoji indicators for line coverage states */
const COVERAGE_ICONS = {
  covered: '🟩',
  partial: '🟨',
  'not-covered': '🟥',
  'no-info': '⬛',
} as const

/** File status icons */
const FILE_STATUS_ICONS = {
  fullyCovered: '🟢',
  hasUncovered: '🔴',
  partialCoverage: '🟠',
} as const

/** Default maximum number of surrounding lines around an uncovered line */
export const DEFAULT_MAX_NUMBER_OF_SURROUNDING_LINES = 1

/** Default maximum characters for markdown output */
export const DEFAULT_MAX_CHARACTERS = 65536

/** Minimum characters required for meaningful markdown output (badges + legend + notice) */
export const MINIMUM_CHARACTERS = 500

/** Options for markdown generation */
export type MarkdownOptions = {
  /** Number of lines to show before and after uncovered lines (default: 1) */
  numberOfSurroundingLines?: number
  /** Maximum number of characters in the output (default: 65536, minimum: 500) */
  maxCharacters?: number
}

/**
 * Generate markdown visualization for coverage packages.
 * This is a pure function suitable for snapshot testing.
 *
 * @param packages - Array of packages
 * @param fileContents - Map of resolved (absolute) path to array of line contents
 * @param options - Optional configuration for markdown generation
 * @returns Markdown string representation
 * @throws Error if maxCharacters is below MINIMUM_CHARACTERS
 */
export function generateMarkdown(
  packages: PackageCoverage[],
  fileContents: Map<string, string[]>,
  options: MarkdownOptions = {},
): string {
  const numberOfSurroundingLines = options.numberOfSurroundingLines ?? DEFAULT_MAX_NUMBER_OF_SURROUNDING_LINES
  const maxCharacters = options.maxCharacters ?? DEFAULT_MAX_CHARACTERS

  // Validate minimum character limit
  if (maxCharacters < MINIMUM_CHARACTERS) {
    throw new Error(`maxCharacters must be at least ${MINIMUM_CHARACTERS}, got ${maxCharacters}`)
  }

  // Generate fixed content (badges and legend)
  const badges = generateCoverageBadges(packages)
  const legend = generateLegend()

  // Generate all package sections with their file contents
  const packageSections: PackageSectionData[] = []
  for (const pkg of packages) {
    const sectionData = generatePackageSectionData(pkg, fileContents, numberOfSurroundingLines)
    if (sectionData !== null) {
      packageSections.push(sectionData)
    }
  }

  // Sort packages
  sortPackages(packageSections)

  // Calculate PR summary metrics from packages (only files with uncovered lines)
  const prMetrics = calculatePRMetrics(packages)

  // Check if all lines are covered (no package sections with uncovered lines)
  const hasUncoveredContent = packageSections.length > 0

  if (!hasUncoveredContent) {
    // No uncovered lines - return badges + summary
    return buildMarkdownForNoUncoveredContent(badges, prMetrics)
  }

  return buildMarkdownWithinLimitFileLevel({
    badges,
    prMetrics,
    legend,
    packageSections,
    maxCharacters,
  })
}

function buildMarkdownForNoUncoveredContent(badges: string, prMetrics: PRMetrics): string {
  const parts: string[] = []

  // Repo Coverage section
  parts.push('## Repo Coverage')
  parts.push(badges)
  parts.push('')
  parts.push('---')
  parts.push('')

  // PR Coverage section
  parts.push('## PR Coverage')
  parts.push('')
  parts.push(generatePRSummaryLine(prMetrics))
  parts.push('')
  parts.push('---')
  parts.push('')
  parts.push(`<sub>Generated by \`coverage-pr-comment\`</sub>`)

  return parts.join('\n')
}

function buildMarkdownWithinLimitFileLevel(params: {
  badges: string
  prMetrics: PRMetrics
  legend: string
  packageSections: PackageSectionData[]
  maxCharacters: number
}): string {
  const { badges, prMetrics, legend, packageSections, maxCharacters } = params

  // Build output with explicit spacing
  let output = '## Repo Coverage\n'
  output += badges + '\n'
  output += '\n---\n\n'
  output += '## PR Coverage\n'
  output += generatePRSummaryLine(prMetrics) + '\n\n'

  // We will always include legend at the end, so every "fit" check reserves room for it.
  const legendWithSeparator = '\n---\n\n' + legend
  const currentLength = output.length + legendWithSeparator.length
  if (currentLength > maxCharacters) {
    // Should not happen with MINIMUM_CHARACTERS, but be safe.
    return (output + legendWithSeparator).slice(0, maxCharacters)
  }

  let omittedFiles = 0
  let omittedPackages = 0

  // Build incrementally: header, then each file
  for (let p = 0; p < packageSections.length; p++) {
    const pkg = packageSections[p]!

    // Check if we can include this package header
    const testOutput = output + pkg.header + '\n'
    if (testOutput.length + legendWithSeparator.length > maxCharacters) {
      // Omit this package and all remaining
      omittedPackages += packageSections.length - p
      for (let i = p; i < packageSections.length; i++) omittedFiles += packageSections[i]!.files.length
      break
    }

    // Include header with empty line after
    output += pkg.header + '\n'

    for (let f = 0; f < pkg.files.length; f++) {
      const file = pkg.files[f]!.content

      // Check if we can fit this file
      // Files are separated by \n\n, last file before --- gets just \n
      const isLastFile = f === pkg.files.length - 1 && p === packageSections.length - 1
      const spacingAfter = isLastFile ? '\n' : '\n\n'
      const testOutputWithFile = output + file + spacingAfter
      if (testOutputWithFile.length + legendWithSeparator.length > maxCharacters) {
        // Can't fit this file or remaining files in this package
        omittedFiles += pkg.files.length - f

        // Also omit all remaining packages completely
        omittedPackages += packageSections.length - (p + 1)
        for (let i = p + 1; i < packageSections.length; i++) omittedFiles += packageSections[i]!.files.length

        p = packageSections.length // break outer
        break
      }

      // Add file with spacing
      output += file + spacingAfter
    }
  }

  // Add truncation notice if anything omitted AND it fits
  if (omittedFiles > 0 || omittedPackages > 0) {
    const notice = generateTruncationNotice(omittedFiles, omittedPackages)
    const testOutputWithNotice = output + notice + '\n\n'
    if (testOutputWithNotice.length + legendWithSeparator.length <= maxCharacters) {
      output += notice + '\n\n'
    }
  }

  // Add horizontal rule and legend
  output += legendWithSeparator

  // Hard guarantee (should already be true)
  if (output.length > maxCharacters) output = output.slice(0, maxCharacters)
  return output
}

/** PR metrics for summary line */
type PRMetrics = {
  coveredLines: number
  totalLines: number
  linePercent: number
  branchPercent: number | null
}

/**
 * Calculate PR coverage metrics from packages (only changed lines).
 * Counts all files, not just ones with uncovered lines.
 */
function calculatePRMetrics(packages: PackageCoverage[]): PRMetrics {
  let coveredLines = 0
  let totalLines = 0
  let branchCovered = 0
  let branchTotal = 0
  let hasBranchData = false

  for (const pkg of packages) {
    for (const file of pkg.files) {
      totalLines += file.lineMetrics.total
      coveredLines += file.lineMetrics.covered

      if (file.branchMetrics) {
        hasBranchData = true
        branchCovered += file.branchMetrics.covered
        branchTotal += file.branchMetrics.total
      }
    }
  }

  const linePercent = totalLines === 0 ? 0 : (coveredLines / totalLines) * 100
  const branchPercent = hasBranchData && branchTotal > 0 ? (branchCovered / branchTotal) * 100 : null

  return {
    coveredLines,
    totalLines,
    linePercent,
    branchPercent,
  }
}

/**
 * Generate PR summary line.
 */
function generatePRSummaryLine(metrics: PRMetrics): string {
  if (metrics.totalLines === 0) {
    return '<b>0/0</b> changed lines covered'
  }

  const linePercentStr = `${Math.round(metrics.linePercent)}%`
  const branchPercentStr = metrics.branchPercent !== null ? `${Math.round(metrics.branchPercent)}%` : 'n/a'

  return `<b>${metrics.coveredLines}/${metrics.totalLines}</b> changed lines covered (Lines: <b>${linePercentStr}</b>, Branches: <b>${branchPercentStr}</b>)`
}

/** Data structure for a package section with its files */
type PackageSectionData = {
  packageName: string
  header: string
  files: FileSectionData[]
  // Metrics for sorting
  totalUncoveredLines: number
  totalPartialBranches: number
}

/** Data structure for a file section */
type FileSectionData = {
  filename: string
  content: string
  // Metrics for sorting
  uncoveredLines: number
  partialBranches: number
}

/**
 * Generate truncation notice with counts of omitted items.
 */
function generateTruncationNotice(omittedFiles: number, omittedPackages: number): string {
  const parts: string[] = []
  if (omittedFiles > 0) {
    parts.push(`${omittedFiles} file(s)`)
  }
  if (omittedPackages > 0) {
    parts.push(`${omittedPackages} package(s)`)
  }
  return `... (${parts.join(' and ')} not shown due to size limit)`
}

/**
 * Generate package section data without joining into final string.
 * Returns null if the package has no files with uncovered lines.
 */
function generatePackageSectionData(
  pkg: PackageCoverage,
  fileContents: Map<string, string[]>,
  numberOfSurroundingLines: number,
): PackageSectionData | null {
  // Check if package has any files with uncovered lines
  const hasUncovered = pkg.files.some(hasUncoveredLines)

  // Skip package entirely if all files are fully covered
  if (!hasUncovered) {
    return null
  }

  // Package header - simple H3 format
  const header = `### ${pkg.name}`

  // Generate file sections - need to include all files, not just uncovered
  const files: FileSectionData[] = []
  let totalUncoveredLines = 0
  let totalPartialBranches = 0

  for (const file of pkg.files) {
    const content = file.resolvedPath ? (fileContents.get(file.resolvedPath) ?? []) : []

    // Calculate metrics for sorting
    const uncoveredLines = file.lines.filter((line) => line.state === 'not-covered').length
    const partialBranches = file.lines.filter((line) => line.state === 'partial').length
    totalUncoveredLines += uncoveredLines
    totalPartialBranches += partialBranches

    files.push({
      filename: file.filename,
      content: generateFileSection(file, content, numberOfSurroundingLines),
      uncoveredLines,
      partialBranches,
    })
  }

  // Sort files within package
  sortFiles(files)

  return {
    packageName: pkg.name,
    header,
    files,
    totalUncoveredLines,
    totalPartialBranches,
  }
}

/**
 * Check if a file has any uncovered or partial lines.
 */
function hasUncoveredLines(file: FileCoverage): boolean {
  return file.lines.some((line) => line.state === 'not-covered' || line.state === 'partial')
}

/**
 * Generate a markdown section for a single file.
 * Uses inline format for fully covered files, details block for files with uncovered lines.
 */
function generateFileSection(file: FileCoverage, fileLines: string[], numberOfSurroundingLines: number): string {
  const fileHasUncovered = hasUncoveredLines(file)

  if (!fileHasUncovered) {
    // Fully covered - use inline format
    const coveredCount = file.lineMetrics.covered
    const totalCount = file.lineMetrics.total
    return `✓ ${FILE_STATUS_ICONS.fullyCovered} <b>${file.filename}</b> — <b>${coveredCount}/${totalCount}</b> changed lines covered`
  }

  // Has uncovered lines - use details block
  const lines: string[] = []

  // Determine file status icon
  // 🔴 if has uncovered lines, 🟠 if only partial branches (no uncovered), 🟢 if fully covered
  const fileHasUncoveredLines = file.lines.some((line) => line.state === 'not-covered')
  const fileHasPartial = file.lines.some((line) => line.state === 'partial')
  const statusIcon = fileHasUncoveredLines
    ? FILE_STATUS_ICONS.hasUncovered
    : fileHasPartial
      ? FILE_STATUS_ICONS.partialCoverage
      : FILE_STATUS_ICONS.fullyCovered

  // Calculate file metrics
  const coveredCount = file.lineMetrics.covered
  const totalCount = file.lineMetrics.total
  const linePercent = totalCount === 0 ? 0 : Math.round((coveredCount / totalCount) * 100)
  const branchPercent = file.branchMetrics
    ? file.branchMetrics.total === 0
      ? 'n/a'
      : `${Math.round((file.branchMetrics.covered / file.branchMetrics.total) * 100)}%`
    : 'n/a'

  // Start collapsible details section
  lines.push(`<details>`)
  lines.push(
    `<summary>${statusIcon} <b>${file.filename}</b> — <b>${coveredCount}/${totalCount}</b> changed lines covered (Lines: <b>${linePercent}%</b>, Branches: <b>${branchPercent}</b>)</summary>`,
  )
  lines.push('')

  // Generate code block with coverage annotations
  const extension = getFileExtension(file.filename)
  lines.push('```' + extension)
  lines.push(generateAnnotatedLines(file.lines, fileLines, numberOfSurroundingLines))
  lines.push('```')
  lines.push('</details>')

  return lines.join('\n')
}

/**
 * Generate annotated line content showing coverage state.
 * Only shows uncovered/partial lines with configurable context lines around them.
 * Uses smart ellipsis handling: shows single lines instead of "..." when gap is small.
 */
function generateAnnotatedLines(
  coverageLines: LineCoverage[],
  fileLines: string[],
  numberOfSurroundingLines: number,
): string {
  if (coverageLines.length === 0) {
    return '(no coverage data)'
  }

  const sortedLines = [...coverageLines].sort((a, b) => a.lineNumber - b.lineNumber)

  // Create a map for quick line lookup
  const lineMap = new Map<number, LineCoverage>()
  for (const line of sortedLines) {
    lineMap.set(line.lineNumber, line)
  }

  // Find all uncovered/partial lines (the "interesting" lines)
  const interestingLineNumbers = new Set<number>()
  for (const line of sortedLines) {
    if (line.state === 'not-covered' || line.state === 'partial') {
      interestingLineNumbers.add(line.lineNumber)
    }
  }

  // Expand to include context lines around interesting lines
  const linesToShow = new Set<number>()
  for (const lineNum of interestingLineNumbers) {
    // Add context before and after
    for (let i = lineNum - numberOfSurroundingLines; i <= lineNum + numberOfSurroundingLines; i++) {
      if (i >= 1 && (i <= fileLines.length || lineMap.has(i))) {
        linesToShow.add(i)
      }
    }
  }

  // Convert to sorted array
  const linesToShowArray = [...linesToShow].sort((a, b) => a - b)

  // Helper to get line content from fileLines (1-indexed to 0-indexed)
  const getLineContent = (lineNum: number): string => {
    const index = lineNum - 1
    if (index >= 0 && index < fileLines.length) {
      return fileLines[index] ?? ''
    }
    return ''
  }

  const outputLines: string[] = []

  // Determine the first and last line numbers in coverage data for ellipsis detection
  const minLineInData = sortedLines[0]?.lineNumber ?? 1
  const maxLineInData = sortedLines[sortedLines.length - 1]?.lineNumber ?? 1
  const firstLineToShow = linesToShowArray[0] ?? minLineInData
  const lastLineToShow = linesToShowArray[linesToShowArray.length - 1] ?? maxLineInData

  // Add leading ellipsis if there's content before the first shown line
  // If only 1 line is hidden, show the actual line instead of ellipsis
  if (firstLineToShow > 1) {
    if (firstLineToShow === 2) {
      // Only line 1 is hidden, show it
      const gapLine = lineMap.get(1)
      const gapIcon = gapLine ? COVERAGE_ICONS[gapLine.state] : COVERAGE_ICONS['no-info']
      const gapLineNumStr = '1'.padStart(3, ' ')
      const gapContent = getLineContent(1)
      outputLines.push(`${gapLineNumStr} ${gapIcon} ${gapContent}`)
    } else {
      outputLines.push('...')
    }
  }

  let prevLineNumber = -1

  for (const lineNum of linesToShowArray) {
    const line = lineMap.get(lineNum)

    // Check for gap and handle ellipsis
    if (prevLineNumber !== -1 && lineNum > prevLineNumber + 1) {
      const gapSize = lineNum - prevLineNumber - 1

      // If gap is just 1 line, show the actual line
      if (gapSize === 1) {
        const gapLineNum = prevLineNumber + 1
        const gapLine = lineMap.get(gapLineNum)
        const gapIcon = gapLine ? COVERAGE_ICONS[gapLine.state] : COVERAGE_ICONS['no-info']
        const gapLineNumStr = gapLineNum.toString().padStart(3, ' ')
        const gapContent = getLineContent(gapLineNum)
        outputLines.push(`${gapLineNumStr} ${gapIcon} ${gapContent}`)
      } else {
        // 2+ line gap: show single ellipsis
        outputLines.push('...')
      }
    }

    const icon = line ? COVERAGE_ICONS[line.state] : COVERAGE_ICONS['no-info']
    const lineNumStr = lineNum.toString().padStart(3, ' ')
    const content = getLineContent(lineNum)
    outputLines.push(`${lineNumStr} ${icon} ${content}`)

    prevLineNumber = lineNum
  }

  // Add trailing ellipsis if there's content after the last shown line
  // If only 1 line is hidden, show the actual line instead of ellipsis
  if (lastLineToShow < fileLines.length) {
    if (lastLineToShow === fileLines.length - 1) {
      // Only the last line is hidden, show it
      const lastLineNum = fileLines.length
      const gapLine = lineMap.get(lastLineNum)
      const gapIcon = gapLine ? COVERAGE_ICONS[gapLine.state] : COVERAGE_ICONS['no-info']
      const gapLineNumStr = lastLineNum.toString().padStart(3, ' ')
      const gapContent = getLineContent(lastLineNum)
      outputLines.push(`${gapLineNumStr} ${gapIcon} ${gapContent}`)
    } else {
      outputLines.push('...')
    }
  }

  return outputLines.join('\n')
}

/**
 * Generate the coverage legend explaining the symbols.
 */
function generateLegend(): string {
  return `<sub>Legend: ${COVERAGE_ICONS['not-covered']} uncovered · ${COVERAGE_ICONS.partial} partial branch · ${COVERAGE_ICONS.covered} covered · ${COVERAGE_ICONS['no-info']} non-executable/blank<br>Generated by \`coverage-pr-comment\`</sub>`
}

/**
 * Generate coverage badges for the overall packages.
 * Returns badges for Line and Branch coverage if data is available.
 * Does NOT include Function/Method coverage badge.
 */
function generateCoverageBadges(packages: PackageCoverage[]): string {
  const metrics = calculateReportMetrics(packages)

  const badges: string[] = []
  badges.push(generateBadge('Line Coverage', metrics.lineMetrics))
  badges.push(generateBadge('Branch Coverage', metrics.branchMetrics ?? { covered: 0, total: 0 }))
  return badges.join('\n')
}

/**
 * Generate a single shields.io badge markdown.
 */
function generateBadge(label: string, metrics?: CoverageMetrics): string {
  const encodedLabel = encodeURIComponent(label)

  // For branch coverage with no data (total === 0), use "n/a" instead of percentage
  let value: string
  let color: string
  if (!metrics || metrics.total === 0) {
    value = 'n/a'
    color = 'brightgreen'
  } else {
    const percent = metrics.total === 0 ? 0 : (metrics.covered / metrics.total) * 100
    value = `${percent.toFixed(2)}%`
    color = getBadgeColor(percent)
  }
  const encodedValue = encodeURIComponent(value)

  return `![${label}](https://img.shields.io/badge/${encodedLabel}-${encodedValue}-${color}.svg?style=flat)`
}

/**
 * Get badge color based on coverage percentage.
 */
function getBadgeColor(percent: number): string {
  if (percent >= 80) return 'brightgreen'
  if (percent >= 60) return 'green'
  if (percent >= 40) return 'yellowgreen'
  if (percent >= 20) return 'yellow'
  return 'red'
}

/**
 * Calculate aggregate metrics for the entire packages.
 */
function calculateReportMetrics(packages: PackageCoverage[]): {
  lineMetrics: CoverageMetrics
  branchMetrics?: CoverageMetrics
} {
  let lineCovered = 0
  let lineTotal = 0
  let branchCovered = 0
  let branchTotal = 0
  let hasBranchData = false

  for (const pkg of packages) {
    for (const file of pkg.files) {
      lineCovered += file.lineMetrics.covered
      lineTotal += file.lineMetrics.total

      if (file.branchMetrics) {
        hasBranchData = true
        branchCovered += file.branchMetrics.covered
        branchTotal += file.branchMetrics.total
      }
    }
  }

  const result: {
    lineMetrics: CoverageMetrics
    branchMetrics?: CoverageMetrics
  } = {
    lineMetrics: { covered: lineCovered, total: lineTotal },
  }

  if (hasBranchData) {
    result.branchMetrics = { covered: branchCovered, total: branchTotal }
  }

  return result
}

/**
 * Extract file extension for syntax highlighting.
 */
function getFileExtension(filename: string): string {
  const parts = filename.split('.')
  if (parts.length < 2) {
    return ''
  }

  const lastPart = parts[parts.length - 1]
  const ext = lastPart ? lastPart.toLowerCase() : ''

  // Map extensions to markdown code block language identifiers
  const extensionMap: Record<string, string> = {
    cs: 'csharp',
    rs: 'rust',
    ts: 'typescript',
    tsx: 'typescript',
    js: 'javascript',
    jsx: 'javascript',
    py: 'python',
    rb: 'ruby',
    go: 'go',
    java: 'java',
    kt: 'kotlin',
    swift: 'swift',
    cpp: 'cpp',
    c: 'c',
    h: 'c',
    hpp: 'cpp',
  }

  return extensionMap[ext] || ext
}

/**
 * Sort packages by uncovered lines, partial branches, then alphabetically.
 */
function sortPackages(packages: PackageSectionData[]): void {
  packages.sort((a, b) => {
    // Sort by total uncovered lines (descending)
    if (a.totalUncoveredLines !== b.totalUncoveredLines) {
      return b.totalUncoveredLines - a.totalUncoveredLines
    }

    // Sort by total partial branches (descending)
    if (a.totalPartialBranches !== b.totalPartialBranches) {
      return b.totalPartialBranches - a.totalPartialBranches
    }

    // Alphabetically by package name (ascending)
    return a.packageName.localeCompare(b.packageName)
  })
}

/**
 * Sort files by uncovered lines, partial branches, then alphabetically.
 * Fully covered files (0 uncovered) come first, then files with uncovered lines.
 */
function sortFiles(files: FileSectionData[]): void {
  files.sort((a, b) => {
    // Fully covered files (0 uncovered) come first
    const aIsFullyCovered = a.uncoveredLines === 0
    const bIsFullyCovered = b.uncoveredLines === 0
    if (aIsFullyCovered !== bIsFullyCovered) {
      return aIsFullyCovered ? -1 : 1
    }

    // For files with uncovered lines, sort by uncovered lines (descending)
    if (!aIsFullyCovered && a.uncoveredLines !== b.uncoveredLines) {
      return b.uncoveredLines - a.uncoveredLines
    }

    // Sort by partial branches (descending)
    if (a.partialBranches !== b.partialBranches) {
      return b.partialBranches - a.partialBranches
    }

    // Alphabetically by filename (ascending)
    return a.filename.localeCompare(b.filename)
  })
}
